import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

import static java.lang.Math.random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class PasswordGenerator {

    List myPassword = new ArrayList<>();

    public String generatePassword(int length, int numberOfSpecialCharacters, int numberOfNumbers) {

        int numberOfLetters = length - numberOfSpecialCharacters - numberOfNumbers;

        myPassword = generateNumbers(length, numberOfNumbers);
        myPassword = generateSpecialCharacters(length, numberOfSpecialCharacters);
        myPassword = generateLetters(numberOfLetters);

        String stringPassword = "";
        Collections.shuffle(myPassword);

        for (Object a : myPassword) {
            stringPassword += a;
        }


        return stringPassword;
    }

    public List generateLetters(int numberOfLetters) {

        for(int i = 0; i < numberOfLetters; i++) {

            String alphabet = "abcdefghijklmnopqrstuvwxyz";
              int a = (int) (Math.random() * 26);

            myPassword.add(0, alphabet.charAt(a));
        }
        return myPassword;
    }


    public List generateSpecialCharacters(int length, int numberOfSpecialCharacters) {

       char[] charArray = {'£', '$', '!', '#', '@', '+', '-', '/', '*'};

       for (int i = 0; i < numberOfSpecialCharacters; i++) {

           int index = (int) (random() * length);
           char randomCharacter = charArray[index];

           myPassword.add(0, randomCharacter);
           }

        return myPassword;
    }



    public List generateNumbers(int length, int numberOfNumbers) {

        for (int i = 0; i < numberOfNumbers; i++) {
            int randomNumber = (int) (Math.random() * 10);
            myPassword.add(0, randomNumber);

        }
        return myPassword;
    }
}

