import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class PasswordGenerator {

    public List<Character> specialCharacter = new ArrayList<>();
    public List<Character> letters = new ArrayList<>();
    public List<Character> numbersList = new ArrayList<>();

    public PasswordGenerator() {
        addSpecialCharacters();
        addNumbers();
        addLetters();
    }

    public String generatePassword(int passwordLength, int specialCharacters, int numbers) {

        String password = "";
        Random random = new Random();

        for (int i = 0; i < specialCharacters; i++) {
            password += specialCharacter.get(random.nextInt(specialCharacter.size()));
            passwordLength--;
        }

        for (int i = 0; i < numbers; i++) {
            password += numbersList.get(random.nextInt(numbersList.size()));
            passwordLength--;
        }

        for (int i = 0; i < passwordLength; i++) {
            password += letters.get(random.nextInt(letters.size()));
        }

        password = mixUpPassword(password);
        return password;
    }

    private void addSpecialCharacters() {
        for (char c = '!'; c <= '/'; c++) {
            specialCharacter.add(c);
        }
        specialCharacter.add('£');
        specialCharacter.add('@');
    }

    private void addNumbers() {
        for (char c = '0'; c <= '9'; c++) {
            numbersList.add(c);
        }
    }

    private void addLetters() {
//        for (char uc = 'A'; uc <= 'Z'; uc++) {
//            letters.add(uc);
//        }
        for (char lc = 'a'; lc <= 'z'; lc++) {
            letters.add(lc);
        }
    }

    private String mixUpPassword(String orderedPassword) {
        char[] passwordArray = orderedPassword.toCharArray();
        List<Character> currentPassword = new ArrayList<>();

        for (char character : passwordArray) {
            currentPassword.add(character);
        }

        Collections.shuffle(currentPassword);

        String newWord = "";
        for (char characters : currentPassword) {
            newWord += characters;
        }
        return newWord;
    }
}
