/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;


public class PasswordGeneratorTest {


    @Test
    public void checkSecretPassword() {

        PasswordGenerator passwordGenerator = new PasswordGenerator();

        BCryptPasswordEncoder bCryptPasswordEncoder = new BCryptPasswordEncoder();

        String secretPassword = passwordGenerator.generatePassword(3,1,1);
        System.out.println(secretPassword);

        String encode;

        do {
            secretPassword = passwordGenerator.generatePassword(3, 1, 1);
            encode = bCryptPasswordEncoder.encode(secretPassword);
            System.out.println(secretPassword + " " + encode);

            if (secretPassword.equals(encode)) {
                System.out.println("Match!");
                System.out.println(secretPassword + " " + encode);
                break;
            }
        } while (!bCryptPasswordEncoder.matches(secretPassword, "$2a$10$N43LdqU9b1ZMuZM2KiBnIeaXiPqxYcTEVoMFabb9ZV2jfG82jupD6"));

    }
}


